// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeatReservation.Api.Infrastructure.Persistence;

#nullable disable

namespace SeatReservation.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid")
                        .HasColumnName("show_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_idempotency_keys");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_idempotency_keys_reservation_id");

                    b.HasIndex("ShowId", "UserId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_idempotency_keys_show_id_user_id_idempotency_key");

                    b.ToTable("idempotency_keys", (string)null);
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.Reservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("AmountPaise")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_paise");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid")
                        .HasColumnName("show_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_reservations");

                    b.HasIndex("ShowId", "UserId")
                        .HasDatabaseName("ix_reservations_show_id_user_id");

                    b.ToTable("reservations", null, t =>
                        {
                            t.HasCheckConstraint("ck_reservations_amount_paise", "amount_paise >= 0");

                            t.HasCheckConstraint("ck_reservations_status", "status IN ('confirmed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.ReservationSeat", b =>
                {
                    b.Property<Guid>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<Guid>("SeatId")
                        .HasColumnType("uuid")
                        .HasColumnName("seat_id");

                    b.HasKey("ReservationId", "SeatId")
                        .HasName("pk_reservation_seats");

                    b.HasIndex("SeatId")
                        .HasDatabaseName("ix_reservation_seats_seat_id");

                    b.ToTable("reservation_seats", (string)null);
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.Seat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid?>("ReservationId")
                        .HasColumnType("uuid")
                        .HasColumnName("reservation_id");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("seat_number")
                        .UseCollation("C");

                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid")
                        .HasColumnName("show_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_seats");

                    b.HasIndex("ReservationId")
                        .HasDatabaseName("ix_seats_reservation_id");

                    b.HasIndex("ShowId", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_seats_show_id_seat_number");

                    b.ToTable("seats", null, t =>
                        {
                            t.HasCheckConstraint("ck_seats_owner_matches_status", "(status = 'available') = (reservation_id IS NULL)");

                            t.HasCheckConstraint("ck_seats_status", "status IN ('available', 'held', 'confirmed')");
                        });
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.Show", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("PerUserLimit")
                        .HasColumnType("integer")
                        .HasColumnName("per_user_limit");

                    b.Property<long>("PricePaise")
                        .HasColumnType("bigint")
                        .HasColumnName("price_paise");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("integer")
                        .HasColumnName("total_seats");

                    b.HasKey("Id")
                        .HasName("pk_shows");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_shows_created_at");

                    b.ToTable("shows", null, t =>
                        {
                            t.HasCheckConstraint("ck_shows_per_user_limit", "per_user_limit > 0");

                            t.HasCheckConstraint("ck_shows_price_paise", "price_paise >= 0");

                            t.HasCheckConstraint("ck_shows_total_seats", "total_seats > 0");
                        });
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.ShowUserLimit", b =>
                {
                    b.Property<Guid>("ShowId")
                        .HasColumnType("uuid")
                        .HasColumnName("show_id");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("user_id");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_count");

                    b.HasKey("ShowId", "UserId")
                        .HasName("pk_show_user_limits");

                    b.ToTable("show_user_limits", null, t =>
                        {
                            t.HasCheckConstraint("ck_show_user_limits_reserved_count", "reserved_count >= 0");
                        });
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.IdempotencyKey", b =>
                {
                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_keys_reservations_reservation_id");

                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Show", null)
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_idempotency_keys_shows_show_id");
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.Reservation", b =>
                {
                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Show", null)
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservations_shows_show_id");
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.ReservationSeat", b =>
                {
                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_seats_reservations_reservation_id");

                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Seat", null)
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reservation_seats_seats_seat_id");
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.Seat", b =>
                {
                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Reservation", null)
                        .WithMany()
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_seats_reservations_reservation_id");

                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Show", null)
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_seats_shows_show_id");
                });

            modelBuilder.Entity("SeatReservation.Api.Infrastructure.Persistence.ShowUserLimit", b =>
                {
                    b.HasOne("SeatReservation.Api.Infrastructure.Persistence.Show", null)
                        .WithMany()
                        .HasForeignKey("ShowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_show_user_limits_shows_show_id");
                });
#pragma warning restore 612, 618
        }
    }
}
